# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Dr. Robert Müller
email: robert.mueller1990@googlemail.com
description: >- # this means to ignore newlines until "baseurl:"
  Senior Data Scientist @ Alexander Thamm.
  PhD in applied Machine Learning from the Mobile and Distributed Systems Group @ LMU Munich.
baseurl: /
url: https://romue404.github.io
twitter_username: romue404
github_username:  romue404

# Build settings
remote_theme: "mmistakes/so-simple-theme@3.2.0"
#theme: jekyll-theme-so-simple
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate

author:
  name:
  picture:
  email:
  twitter:
  links:
    - title:
      url:
      icon:

# own additions
skin: "/assets/css/skins/romue.css"

google_fonts:
  - name: "Roboto"
    weights: "400,400i,700,700i"

date_format: "%B %-d, %Y"

logo: "/images/me.webp"

liquid:
  error_mode: strict

permalink: /:categories/:title/
markdown: kramdown
mathjax:
  enable: true
  combo: "tex-svg"
  tags: "ams"

paginate: 10  # amount of posts to show per page
paginate_path: /page:num/

locale: en-US
